project_name: discovery-engine

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - binary: discovery-engine
    id: discovery-engine
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
        #- windows
        #- darwin
    goarch:
      - amd64
      
archives:
  - id: "discovery-engine"
    builds:
      - "discovery-engine"
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - src: ./conf/local-file.yaml
        dst: /opt/discovery-engine/local-file.yaml
        strip_parent: true
      - src: ./packaging/discovery-engine.service
        dst: /usr/lib/systemd/system
        strip_parent: true
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - id: "discovery-engine"
    builds:
      - "discovery-engine"
    formats:
      - deb
      - rpm
    replaces:
      - discovery-engine
    maintainer: "Ankur Kothiwal <ankur.kothiwal@accuknox.com>"
    description: |
      Auto policy discovery engine
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    bindir: /
    contents:
      - dst: /opt/discovery-engine
        type: dir
      - src: ./conf/local-file.yaml
        dst: /opt/discovery-engine/local-file.yaml
        type: config
      - src: ./packaging/discovery-engine.service
        dst: /usr/lib/systemd/system/discovery-engine.service
        type: config
      - src: /opt/src/discovery-engine
        dst: /usr/local/bin/discovery-engine
        type: symlink
    scripts:
      postinstall: packaging/post-install.sh
    overrides:
      deb:
        dependencies:
          - make
      rpm:
        dependencies:
          - make

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
